caught.burn:
	try {
		3 + "3"
	} catch $e {
		print "caught"
	}

$ $BURN caught.burn
	* stdout
		caught

caught_type.burn:
	try {
		3 + "3"
	} catch TypeError $e {
		print "caught"
	}

$ $BURN caught_type.burn
	* stdout
		caught

caught_types.burn:
	try {
		3 + "3"
	} catch ArgumentError $e {
		print "ArgumentError"
	} catch TypeError $e {
		print "TypeError"
	}

$ $BURN caught_types.burn
	* stdout
		TypeError

uncaught_type.burn:
	try {
		3 + "3"
	} catch ArgumentError $e {
		print "ArgumentError"
	}

$ $BURN uncaught_type.burn
	* exit status nonzero
